### PR TITLE
Exercise15

### PR DESCRIPTION
**Pull request by clucksupremacy**
Something about the if-else structuring feels redundant. Is it sound here, or would it be better with a different type of statement?

### CODE REVIEW

**Comment by Aceeri** [comment]
Ya I would try removing some of the conditions here, also try using just less than and greater than operators rather than offsetting the magic numbers like 800 by 1.

**Comment by clucksupremacy** [comment]
Is this any better?

**Comment by Aceeri** [comment]
> Is this any better?

Try instead of having 2 conditions, rely on the other conditions you made beforehand here. You have a condition for if it is less than 500, but then check in the else if it is greater, but you already know it can't be less than 500 right?

**Comment by clucksupremacy** [comment]
bam

**Review by Aceeri — APPROVED** [review]

**Pull request merged**
